### PR TITLE
Upgrade dependencies for Symfony 3

### PR DESCRIPTION
**Pull request by mattsches**
Include Symfony components in version 3 and fix versioning scheme for rybakit/arguments-resolver.

Hi Robert, I was trying to install [mattsches/VersionEyeBundle](https://github.com/mattsches/VersionEyeBundle) in a Symfony3 project, but it failed. This is an attempt to resolve the dependency problems.

### CODE REVIEW

**Comment by digitalkaoz** [comment]
Merci

**Comment by digitalkaoz** [comment]
@mattsches can you fix the style Checks? Otherwise im unable to merge from my phone. Im on vacations now, so i dont have my work Laptop with me

**Comment by mattsches** [comment]
@digitalkaoz I applied the fixes for the style checks, but StyleCI is still complaining? Not sure what to do now because I'm new to StyleCI.

But no worries, I'm not in a hurry re: my VersionEyeBundle, enjoy your vacation!

**Comment by digitalkaoz** [comment]
@mattsches done, thank you!

**Comment by mattsches** [comment]
Could you please create a new release for this (0.11.3 or so) so that my Bundle can fetch the update when doing a `composer install`?

**Comment by digitalkaoz** [comment]
@mattsches done https://github.com/digitalkaoz/versioneye-php/releases/tag/0.11.3

**Pull request merged**
