### PR TITLE
Use stable version of the multipart stream builder

### PR DESCRIPTION
**Pull request by Nyholm**
There is one thing that might be considered as a BC break. If we, for whatever reason, added multiple streams/post data with the same name. Before they were overridden but since 0.2.0 we do allow duplicate values.

### CODE REVIEW

**Comment by digitalkaoz** [comment]
as we dont have duplicates i think this is perfectly fine. thanks for your PR!

**Comment by Nyholm** [comment]
Thank you for merging.

**Comment by digitalkaoz** [comment]
@Nyholm it seems there is a problem with php-http-plug and guzzle in php 7.2 https://travis-ci.org/digitalkaoz/versioneye-php/jobs/234743164 maybe you can have a look?

**Comment by Nyholm** [comment]
That will be fixed in the next release of Guzzle. See https://github.com/guzzle/guzzle/commit/375c01b636cbbe967d4b180628abdf94c0b9070f

**Comment by digitalkaoz** [comment]
ah i only looked in master and it was already an array...didnt thought of that this is not part of the latest tag...thanks!

**Comment by Nyholm** [comment]
I was also surprised. This fix was made 5 months ago.

**Pull request merged**
